// web/src/components/rate-limit-counter.tsx
import { Timer } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { useAppStore } from "@/lib/store";

export function RateLimitCounter({ allowSmall }: { allowSmall?: boolean }) {
  const clientState = useAppStore((s) => s.clientState);
  const remaining = clientState.ratelimit_remaining ?? 0;
  const limit = clientState.ratelimit_limit ?? 0;
  const percent = limit > 0 ? Math.floor((remaining / limit) * 100) : 0;

  const label = `${remaining.toLocaleString()} left of ${limit.toLocaleString()} limit`;

  if (!percent && !limit) {
    return null;
  }

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Badge
          variant="secondary"
          className="max-w-full min-w-0 justify-start font-mono text-xs"
          data-testid="rate-limit-badge"
        >
          <Timer className="size-3.5 shrink-0" aria-hidden />
          <span className="min-w-0 truncate">
            {percent}%<span className={allowSmall ? "max-md:hidden" : "hidden md:inline"}> calls left</span>
          </span>
        </Badge>
      </TooltipTrigger>
      <TooltipContent>{label}</TooltipContent>
    </Tooltip>
  );
}

// public/src/components/rate-limit-counter.vue
<template>
  <CoreTooltip :label="label">
    <n-tag type="info" v-bind="$attrs">
      <template #icon>
        <n-icon><i-mdi-timer-sync-outline /></n-icon>
      </template>
      {{ percent }}% <span :class="{ 'hidden md:inline-flex': props.allowSmall }">calls left</span>
    </n-tag>
  </CoreTooltip>
</template>

<script setup lang="ts">
const props = defineProps<{
  allowSmall?: boolean
}>()

const state = useState()

const remaining = computed(() => state.clientState.ratelimit_remaining ?? 0)
const limit = computed(() => state.clientState.ratelimit_limit ?? 0)
const label = computed(() => {
  return `${remaining.value.toLocaleString()} left of ${limit.value.toLocaleString()} limit`
})

const percent = computed(() => {
  return Math.floor((remaining.value / limit.value) * 100)
})
</script>
